### ISSUE TITLE
Nice to have: mock capability

### ISSUE THREAD

**Issue by mdhooge** [lightsofapollo/superagent-promise#11]
The Promise extension to superagent is not compatible with the superagent-mock plugin (https://github.com/M6Web/superagent-mock).

Since that plugin changes method of the Request object, I tried to provide it with the PromiseRequest by adding the line:
```request.Request = PromiseRequest;```

But it modifies the end() method, so the problem is "deeper" than I thought. And I don't see how to cleverly solve it :-(

Thanks
Michel

**Comment by clayreimann** [comment]
@mdhooge I've got some tests that show how you'll be able to use superagent-promise with superagent-mock after superagent-mock merges [my PR](https://github.com/clayreimann/superagent-mock/pull/1) on their project. Feel free to bother them to merge it.

**Comment by clayreimann** [comment]
This was closed by #13 and is now documented in the readme.
