### ISSUE TITLE
Set custom headers

### ISSUE THREAD

**Issue by amannn** [lightsofapollo/superagent-promise#17]
Is this possible with the current implementation?

**Comment by clayreimann** [comment]
It should be. Have you tried to set headers?

If so what have you tried?

**Comment by amannn** [comment]
Actually I just looked through `index.js` to see if I can find an API method to set headers, but couldn't find anything. I didn't try anything yet. But I switched to superagent itself then, so I'm not in need of this feature anymore. Thanks anyway!

**Comment by astoltzfus** [comment]
I'm wondering the same thing. I looked through `index.js` but couldn't find any method either. I would like to switching to another implementation. @clayreimann & @lightsofapollo - is this possible?

**Comment by clayreimann** [comment]
This module is a very thin wrapper around `SuperAgent` proper. You can use the standard `SuperAgent` method of [setting headers](http://visionmedia.github.io/superagent/#setting-header-fields). That's what I do, if it doesn't work for you please post what's not working for you.

**Comment by clayreimann** [comment]
I assume that you guys have found what you need.
