### ISSUE TITLE
How to abort a request.

### ISSUE THREAD

**Issue by codeocelot** [lightsofapollo/superagent-promise#23]
Is there a way to abort requests similar to XMLHttpRequest?  (https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort) ?

**Comment by clayreimann** [comment]
There is not, cancelling a promise is not part of the A+ spec so it's unclear what the API would be and how the promise would be notified of the cancellation.

If you want to address this feel free to submit a PR.

**Comment by erasmo-marin** [comment]
What would be the right way to implement this?

I was thinking to provide a way to return the original request object, so you can access all methods, like abort, so you can listen to the abort event.

**Comment by clayreimann** [comment]
The only way I can think of doing this cleanly would be to return a Promise with augmented API alá [Bluebird](http://bluebirdjs.com/docs/getting-started.html). It should be noted that superagent supports a promise-like API since 3.0 so this project is pretty dead at this point.
